Minor improvements and fixes
chrultrabook/docs pull request #101
Opened 2023-11-07 03:07 UTC by WeirdTreeThing

Separate flashing fw and updating fw
Fix a typo
Add linux keyboard remap info to faq

2023-11-07 03:45 UTC, meghan06 submitted a review, later dismissed

2023-11-08 02:42 UTC, mine-man3000 approved these changes

2023-11-08 19:58 UTC, ninelore requested changes

2023-11-08 19:58 UTC, ninelore commented on docs/updating-firmware.md
On Linux booting a live USB is not required. You can flash straight out of your running system

2023-11-09 12:29 UTC, ninelore commented on docs/updating-firmware.md
fixed in f8b86b5

2023-11-09 12:29 UTC, ninelore approved these changes

2023-11-10 00:58 UTC, meghan06 approved these changes

2023-11-10 00:58 UTC, merged