Some grammar/spelling errors.
chrultrabook/docs pull request #113
Opened 2023-11-27 09:58 UTC by actuallyarm64

im currently reading the whole documentation. Please do not merge until ALL spelling or grammar errors have been fixed. Thank you.

2023-11-30 06:13 UTC, meghan06 requested changes
You should distinguish that some CBs open up via back and some via keyboard. Also read comments.

2023-11-30 06:13 UTC, meghan06 commented on src/docs/unbricking/index.md
> +        - In some Chromebooks, you eill need to remove the keyboard, and as mentioned in [Disabling write protect via Battery](/firmware/battery.html), theres a ribbon wire thats needs to be CAREFULL
"Will" is spelled wrong. 

This sentence should be reworded. Current wording makes it sound like all Chromebooks have this cable.

2023-11-30 06:13 UTC, meghan06 commented on src/docs/unbricking/index.md
> +        - In some Chromebooks, you eill need to remove the keyboard, and as mentioned in [Disabling write protect via Battery](/firmware/battery.html), theres a ribbon wire thats needs to be CAREFULL
Typo. 

See previous comment too

2023-11-30 06:16 UTC, actuallyarm64 commented on src/docs/unbricking/index.md
> +        - In some Chromebooks, you eill need to remove the keyboard, and as mentioned in [Disabling write protect via Battery](/firmware/battery.html), theres a ribbon wire thats needs to be CAREFULL
Im on it 👍

2023-12-04 17:26 UTC, ethanaobrien commented on src/docs/unbricking/index.md
> +        - Some Chromebooks open up via back and some via keyboard, and as mentioned in [Disabling write protect via Battery](/firmware/battery.html). On keyboard, you have to pry it out and remove a
Did you forget to push or something?

2023-12-04 18:26 UTC, WeirdTreeThing approved these changes

2023-12-04 22:41 UTC, actuallyarm64 commented
> Waiting on the changes I requested to be addressed

They are already there

2023-12-04 22:49 UTC, ethanaobrien approved these changes

2023-12-04 23:04 UTC, WeirdTreeThing approved these changes

2023-12-04 23:04 UTC, merged