Updated info for SARIEN
chrultrabook/docs pull request #140
Opened 2024-02-17 01:35 UTC by archisman-panigrahi

Updated info for SARIEN Chromebook.

Full UEFI is not supported in this Chromebook, but everything I tested works under RW_Legacy firmware with Linux Mint.

2024-03-31 04:41 UTC, meghan06 approved these changes
@ethanaobrien Looks good to me

2024-03-31 04:59 UTC, archisman-panigrahi commented
Just wanted to clarify that the speaker and mic work out-of-the box without the audio script by WeirdTreeThing.

2024-04-10 10:10 UTC, ninelore requested changes
![image](https://github.com/chrultrabook/docs/assets/21343557/01755d97-7f62-4036-9c04-0708278afe20)
Could be slimmed down

2024-04-10 10:11 UTC, ninelore commented
also link broken

2024-04-10 13:22 UTC, archisman-panigrahi commented
@ninelore  I fixed the link and trimmed it down a little bit.

2024-04-10 13:38 UTC, archisman-panigrahi commented
I cut it down. I will wait for WeirdTreeThing's reply.

2024-04-10 15:14 UTC, WeirdTreeThing commented
> Still very long imo. I'd cut it down to what not works.
> 
> @WeirdTreeThing could you integrate the sarien keymap into cros-keyboard-map? Maybe we can leave out the keyd part altogether

Sure

2024-04-10 21:58 UTC, WeirdTreeThing commented
It has been added to the script now

2024-04-11 04:18 UTC, archisman-panigrahi commented
Check it now.

2024-04-16 16:02 UTC, ninelore approved these changes
LGTM

2024-04-27 12:21 UTC, ethanaobrien approved these changes

2024-04-27 12:26 UTC, merged