Update Darkmode
chrultrabook/docs pull request #204
Opened 2024-09-15 06:53 UTC by death7654

-Improves visuals
-Improves contrast
-Update 'Chrultrabook-Controller' app name to 'Chrultrabook-Tools'
-Add A Placeholder To The Search Bar In `Supported Devices`
-Match Search Bar Styling to Nav Search Bar in `Supported Devices`
-Make Danger Tip Have Better Contrast
-Make Nav Items Larger for better Accessibility

Before
<img width="620" alt="image" src="https://github.com/user-attachments/assets/11420992-7a2e-4da7-ad1b-23b8ada28904">
<img width="665" alt="image" src="https://github.com/user-attachments/assets/68df18ab-43e5-4d8b-9502-4073aae8875d">

After
<img width="613" alt="image" src="https://github.com/user-attachments/assets/c5cc5a39-3fdc-4dfc-9b22-b62ae5eeb738">
<img width="632" alt="image" src="https://github.com/user-attachments/assets/e0b8d902-be9c-4c2b-998c-dcd83359f456">

2024-09-15 06:56 UTC, death7654 commented
This is a continuation of [https://github.com/chrultrabook/docs/pull/186](url). However, I am unable to reopen it as i force pushed my local changes to the cloud.

2024-09-16 05:18 UTC, ninelore commented
Please do not merge prior to a Lighthouse check

2024-09-16 10:17 UTC, death7654 commented
Lighthouse checks report no changes in accessibility, seo, or best practices.

2024-09-16 10:37 UTC, ninelore commented
> Lighthouse checks report no changes in accessibility, seo, or best practices.

Pls send full html report

2024-09-16 15:16 UTC, death7654 commented
> > Lighthouse checks report no changes in accessibility, seo, or best practices.
> 
> Pls send full html report

sent in discord

2024-09-16 15:28 UTC, death7654 commented
[download.pdf](https://github.com/user-attachments/files/17015543/download.pdf)
[download2.pdf](https://github.com/user-attachments/files/17015545/download2.pdf)

Download2 refers to the updated CSS variables and placeholder changes

2024-09-19 17:15 UTC, ninelore approved these changes

2024-09-19 17:46 UTC, MrChromebox commented
personally, I think the changes in color and contrast make things far less readable, I'm not a fan at all

2024-09-19 18:15 UTC, ninelore requested changes
please undo font changes

tip, warning and danger font colors could use more contrast in both dark and light mode

2024-09-20 10:50 UTC, death7654 commented
> personally, I think the changes in color and contrast make things far less readable, I'm not a fan at all

How are the updated colors?

<img width="960" alt="image" src="https://github.com/user-attachments/assets/163aea17-78aa-49e5-a3a1-46c34d4e555a">
<img width="960" alt="image" src="https://github.com/user-attachments/assets/c09baef4-5f8f-465b-bff9-7ab67ae576b3">
<img width="960" alt="image" src="https://github.com/user-attachments/assets/2cde3217-17eb-4f5e-8195-34f5a3550800">
<img width="960" alt="image" src="https://github.com/user-attachments/assets/b172461b-5b83-4e57-ac61-fe8fc0627f3f">

2025-01-29 03:24 UTC, ninelore commented
Obsolete since alot has changed in upstream vuepress

2025-01-29 03:24 UTC, closed without merging