Fix chromium links
chrultrabook/docs pull request #209
Opened 2024-10-03 20:40 UTC by Owen-sz

All Chromium docs links in devices.json give 404, as the upstream links seemed to have changed. These are the proper links.

2024-10-03 20:45 UTC, ninelore approved these changes
Images on upstream pages are broken. Maybe we need an alternative.

Otherwise LGTM

2024-10-03 20:47 UTC, ninelore requested changes
Just saw rebase is required due to merge conflicts (probably due to #208)

2024-10-03 21:23 UTC, Owen-sz commented
> Just saw rebase is required due to merge conflicts (probably due to #208)

Should be good now

2024-10-04 13:50 UTC, ninelore requested changes
Something is not quite right
![image](https://github.com/user-attachments/assets/63a48d6f-eec9-48ba-84e4-af2cd8ef9990)

2024-10-04 14:06 UTC, ethanaobrien commented
Can second ninelore. This has to do with the device property (list of device names) `device.device.join("<br>")`

PR is very difficult to review with the change in spacing, since it shows every line has changed. If possible, could we restore 4 spacing or use 2 separate commits

2024-10-05 23:30 UTC, Owen-sz commented
Fixed it

2024-10-05 23:45 UTC, ethanaobrien approved these changes

2024-10-06 11:30 UTC, ninelore commented
We have local image links that are 404. ToDo check where they went

2024-10-06 17:46 UTC, Owen-sz commented
> We have local image links that are 404. ToDo check where they went

Which images?

2024-10-07 23:15 UTC, Owen-sz commented
I don't know where the Chromium images went, not seeing anything about it.

2024-10-07 23:26 UTC, ninelore commented
I will investigate it soon dw

2024-10-07 23:27 UTC, ninelore approved these changes

2024-10-07 23:27 UTC, merged