Remove Ubuntu warning + add custom kernel warning for debian
chrultrabook/docs pull request #95
Opened 2023-10-31 23:39 UTC by CoolPenguin27

This PR updates the docs about the situation of Ubuntu and adds a custom kernel warning for Debian in [installing-linux.md](https://github.com/chrultrabook/docs/blob/main/docs/installing-linux.md)

2023-11-01 00:51 UTC, WeirdTreeThing requested changes

2023-11-01 00:51 UTC, WeirdTreeThing commented on docs/faq.md
> -
Instead of deleting, mention that using the latest release instead of lts will work better.

2023-11-01 00:51 UTC, WeirdTreeThing commented on docs/installing-linux.md
> +Debian 12 (Bookworm) requires a custom kernel, the [audio script](https://chrultrabook.github.io/docs/docs/installing-linux.html#fixing-audio) will automatically install it for you.
and older versions of debian are not supported

2023-11-01 11:22 UTC, WeirdTreeThing approved these changes

2023-11-02 01:19 UTC, ninelore requested changes
After testing 23.10 myself I still dont think that we should exempt it. 

We explicitly write something along the lines that we may not provide support on discord for ubuntu-based anyway.

Aside from that Ubuntu-based derivatives probably will still have issues because its impossible to test them all. I think they should stay unsupported

2023-11-02 02:56 UTC, WeirdTreeThing commented
Can you write a list of the issues you had with it?

2023-11-02 03:20 UTC, mine-man3000 reviewed
Looks fine to me.

2023-11-02 07:11 UTC, ninelore approved these changes
Merge it for now, but we might need to revert if the problems become excessive in discord

2023-11-02 07:11 UTC, merged